[llvm]
optimize = true
release-debuginfo = false
ccache = "/usr/local/bin/ccache"
ninja = true
#static-libstdcpp = true

#cflags = ""
#cxxflags = ""
#ldflags = ""

[build]

build-stage = 2
test-stage = 2
doc-stage = 2

host = ["x86_64-unknown-linux-musl"]
target = ["x86_64-unknown-linux-musl"]

extended = true
cargo-native-static = true

#tools = ["cargo", "clippy", "rustfmt", "analysis", "src"] 

[install]

prefix = "/mmc"
sysconfdir = "etc"

[rust]

optimize = true
debug = false
description = "tomatoware"
rpath = false
channel = "stable"

[target.x86_64-unknown-linux-musl]

cc = "/opt/tomatoware/x86_64-musl-mmc/bin/x86_64-tomatoware-linux-musl-gcc"
cxx = "/opt/tomatoware/x86_64-musl-mmc/bin/x86_64-tomatoware-linux-musl-g++"
ar = "/opt/tomatoware/x86_64-musl-mmc/bin/x86_64-tomatoware-linux-musl-ar"
ranlib = "/opt/tomatoware/x86_64-musl-mmc/bin/x86_64-tomatoware-linux-musl-ranlib"
linker = "/opt/tomatoware/x86_64-musl-mmc/bin/x86_64-tomatoware-linux-musl-gcc"

musl-root = "/opt/tomatoware/x86_64-musl-mmc/x86_64-tomatoware-linux-musl/sysroot"

crt-static = false

[dist]

src-tarball = false
compression-formats = ["gz"]
